import { StyleSheet } from "react-native";

import {
  ANDROID_TAB_WRAP_HEIGHT,
  HEADER_CONTENT_HEIGHT,
  LOADING_BACKGROUND_COLOR,
} from "./constants";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#fff",
  },
  mainContent: {
    flex: 1,
    position: "relative",
  },
  webviewWrap: {
    flex: 1,
    marginTop: -20,
    paddingTop: 20,
    backgroundColor: LOADING_BACKGROUND_COLOR,
  },
  webview: {
    backgroundColor: LOADING_BACKGROUND_COLOR,
  },
  headerAnimatedWrap: {
    height: HEADER_CONTENT_HEIGHT,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: "#fff",
    overflow: "hidden",
    zIndex: 30,
  },
  headerHiddenWrap: {
    height: 0,
  },
  inlineGuardOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  inlineGuardCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 28,
    // backgroundColor: "#F7F7F8",
    paddingHorizontal: 20,
    paddingVertical: 24,
    alignItems: "center",
  },
  inlineGuardImage: {
    width: 180,
    height: 140,
    marginBottom: 16,
  },
  inlineGuardTitle: {
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "700",
    color: "#131314",
    textAlign: "center",
  },
  inlineGuardText: {
    marginTop: 10,
    fontSize: 15,
    lineHeight: 21,
    color: "#58595E",
    textAlign: "center",
  },
  inlineGuardButton: {
    marginTop: 18,
    borderRadius: 58,
    backgroundColor: "#FE946E",
    paddingHorizontal: 22,
    paddingVertical: 11,
  },
  inlineGuardButtonText: {
    color: "#fff",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
  },
  header: {
    height: HEADER_CONTENT_HEIGHT,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  brandPressable: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 42,
    justifyContent: "center",
  },
  brandLogo: {
    width: 42,
    height: 42,
  },
  brandText: {
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "600",
    color: "#131314",
  },
  walletBadge: {
    minHeight: 26,
    paddingHorizontal: 5,
    borderRadius: 96,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    backgroundColor: "transparent",
  },
  walletIcon: {
    color: "#131314",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
  walletText: {
    color: "#131314",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
  },
  loginButton: {
    borderRadius: 58,
    backgroundColor: "#FE946E",
    paddingHorizontal: 22,
    paddingVertical: 10,
  },
  loginButtonText: {
    color: "#fff",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
  },
  androidTabBarWrap: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 14,
    backgroundColor: "transparent",
  },
  androidTabBarAnimatedWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: ANDROID_TAB_WRAP_HEIGHT,
    overflow: "hidden",
    backgroundColor: "transparent",
    zIndex: 40,
    elevation: 40,
  },
  androidTabBar: {
    position: "relative",
    height: 66,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.95)",
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 50,
    padding: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  androidTabActivePill: {
    position: "absolute",
    top: 4,
    left: 0,
    height: 58,
    borderRadius: 999,
    backgroundColor: "rgba(230,230,235,0.90)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.85)",
  },
  androidTabItem: {
    flex: 1,
    height: "100%",
    zIndex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  androidTabLabel: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "600",
    color: "#757575",
    marginTop: 2,
  },
  androidTabLabelActive: {
    color: "#FE946E",
  },
  androidCartBadge: {
    position: "absolute",
    top: -6,
    right: -10,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    backgroundColor: "#131314",
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  androidCartBadgeText: {
    color: "#fff",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "700",
  },
});
