import { StyleSheet } from "react-native";

import { nativeShellStyles } from "@/components/native-shell-styles";

export const nativeProfileStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F8F8F8",
  },
  nativePageHeaderWrap: {
    width: "100%",
    zIndex: 10,
    backgroundColor: "#FFFFFF",
  },
  pageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 18,
    paddingHorizontal: 16,
    paddingBottom: 18,
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  pageTitle: {
    fontSize: 25,
    lineHeight: 22,
    fontWeight: "500",
    color: "#131314",
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
    backgroundColor: "#F8F8F8",
    gap: 8,
  },
  scroll: {
    flex: 1,
  },
  contentWithAndroidTabBar: {
    paddingBottom: 8,
  },
  profileCard: {
    marginBottom: 8,
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    padding: 16,
  },
  profileCardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  profileAvatar: {
    width: 52,
    height: 52,
    borderRadius: 999,
    backgroundColor: "#933DFF",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  profileAvatarText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  profileAvatarImage: {
    width: "100%",
    height: "100%",
  },
  profileBody: {
    flex: 1,
    minWidth: 0,
  },
  profileName: {
    fontSize: 16,
    lineHeight: 22,
    color: "#0B0B0B",
  },
  profilePhone: {
    marginTop: 2,
    fontSize: 14,
    lineHeight: 16,
    color: "#7C7C7C",
  },
  profileAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    marginLeft: 8,
  },
  profileActionText: {
    fontSize: 14,
    lineHeight: 16,
    color: "#7C7C7C",
  },
  skeletonAvatar: {
    width: 52,
    height: 52,
    borderRadius: 999,
    backgroundColor: "#EFEFF2",
  },
  skeletonLine: {
    borderRadius: 999,
    backgroundColor: "#EFEFF2",
  },
  skeletonNameLine: {
    width: "62%",
    height: 18,
  },
  skeletonPhoneLine: {
    width: "44%",
    height: 14,
    marginTop: 8,
  },
  skeletonActionLine: {
    width: 72,
    height: 16,
    borderRadius: 999,
    backgroundColor: "#EFEFF2",
    marginLeft: 8,
  },
  errorBox: {
    marginBottom: 8,
    borderRadius: 16,
    backgroundColor: "#FFEDEF",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  errorText: {
    fontSize: 14,
    color: "#B72136",
  },
  loyaltyCard: {
    overflow: "hidden",
    borderRadius: 24,
    backgroundColor: "#121212",
    padding: 16,
    minHeight: 140,
  },
  loyaltyContent: {
    gap: 14,
  },
  loyaltyTop: {
    gap: 6,
  },
  loyaltyCaption: {
    fontSize: 13,
    lineHeight: 16,
    color: "rgba(255,255,255,0.3)",
  },
  loyaltyLevelTrail: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "nowrap",
    gap: 8,
  },
  loyaltyLevelItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    maxWidth: "100%",
  },
  loyaltyLevelText: {
    fontSize: 18,
    lineHeight: 24,
    color: "rgba(255,255,255,0.3)",
  },
  loyaltyLevelTextActive: {
    fontSize: 20,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  loyaltyHint: {
    minHeight: 14,
    fontSize: 12,
    lineHeight: 14,
    color: "#FFFFFF",
  },
  loyaltyProgressTrack: {
    position: "relative",
    height: 8,
    justifyContent: "center",
    marginTop: 2,
    paddingHorizontal: 4,
  },
  loyaltyProgressFill: {
    position: "absolute",
    left: 4,
    top: 3,
    height: 2,
    backgroundColor: "#D7FE03",
  },
  loyaltyDotsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  loyaltyDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#646464",
  },
  loyaltyDotActive: {
    backgroundColor: "#D7FE03",
  },
  loyaltyTierLabels: {
    marginTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 0,
  },
  loyaltyTierLabel: {
    flex: 1,
    fontSize: 10,
    lineHeight: 12,
    color: "#FFFFFF",
    textAlign: "center",
  },
  skeletonLineDark: {
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  skeletonCaptionLine: {
    width: 118,
    height: 14,
  },
  skeletonLevelLine: {
    width: "54%",
    height: 22,
  },
  skeletonHintLine: {
    width: "68%",
    height: 14,
  },
  skeletonProgressTrack: {
    height: 8,
    justifyContent: "center",
    marginTop: 2,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  skeletonProgressFill: {
    width: "38%",
    height: 8,
    borderRadius: 999,
    backgroundColor: "rgba(215,254,3,0.35)",
  },
  skeletonTierLabels: {
    marginTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  skeletonTierLabelLine: {
    flex: 1,
    height: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.13)",
  },
  menuWrap: {
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  creditWrap: {
    paddingTop: 16,
    paddingBottom: 4,
  },
  developerCreditLink: {
    marginTop: 80,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  developerCreditText: {
    fontSize: 14,
    lineHeight: 16,
    color: "#7C7C7C",
  },
  developerCreditBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  developerCreditIconWrap: {
    width: 20,
    height: 20,
    borderRadius: 4,
    backgroundColor: "#D7FE03",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  developerCreditBrand: {
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "500",
    color: "#0B0B0B",
  },
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 17,
  },
  menuRowActive: {
    backgroundColor: "rgba(0, 0, 0, 0.03)",
  },
  menuRowBorder: {
    borderTopWidth: 1,
    borderTopColor: "#F1F1F3",
  },
  menuLabel: {
    flex: 1,
    fontSize: 16,
    lineHeight: 22,
    color: "#181818",
  },
  menuLabelDanger: {
    flex: 1,
    fontSize: 16,
    lineHeight: 22,
    color: "#FF425A",
  },
  menuValue: {
    fontSize: 14,
    lineHeight: 20,
    color: "#7C7C7C",
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  contactRowBorder: {
    borderTopWidth: 1,
    borderTopColor: "#F1F1F3",
  },
  contactRowDisabled: {
    opacity: 0.55,
  },
  contactSectionHeader: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 6,
  },
  contactBody: {
    flex: 1,
    minWidth: 0,
  },
  contactLabel: {
    fontSize: 16,
    lineHeight: 20,
    color: "#181818",
  },
  contactValue: {
    marginTop: 2,
    fontSize: 14,
    lineHeight: 18,
    color: "#7C7C7C",
  },
  loginPrompt: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  loginTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#131314",
    textAlign: "center",
  },
  loginText: {
    marginTop: 10,
    fontSize: 15,
    lineHeight: 21,
    color: "#58595E",
    textAlign: "center",
  },
  loginButton: {
    marginTop: 18,
    borderRadius: 58,
    backgroundColor: "#FE946E",
    paddingHorizontal: 22,
    paddingVertical: 11,
  },
  loginButtonText: {
    color: "#fff",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
  },

  hybridHeader: nativeShellStyles.header,
  hybridHeaderCompact: nativeShellStyles.headerCompact,
  hybridHeaderWrap: nativeShellStyles.headerAnimatedWrap,
  hybridHeaderWrapCompact: nativeShellStyles.headerAnimatedWrapCompact,
  headerTopRow: nativeShellStyles.headerTopRow,
  walletBadge: nativeShellStyles.walletBadge,
  walletText: nativeShellStyles.walletText,
  loginTopButton: nativeShellStyles.loginButton,
  loginTopButtonText: nativeShellStyles.loginButtonText,
  androidTabBarAnimatedWrap: nativeShellStyles.androidTabBarAnimatedWrap,
  androidTabBarWrap: nativeShellStyles.androidTabBarWrap,
  androidTabBar: nativeShellStyles.androidTabBar,
  androidTabActivePill: nativeShellStyles.androidTabActivePill,
  profileWalletBadge: {
    minHeight: 26,
    paddingHorizontal: 8,
    gap: 3,
  },
  profileWalletText: {
    fontSize: 14,
    lineHeight: 16,
  },
});
