import { StyleSheet } from "react-native";

export const supportColors = {
  background: "#FFFFFF",
  border: "#ECECEE",
  muted: "#747479",
  text: "#131314",
  dangerBg: "#FFEDEF",
  dangerText: "#B72136",
  bubbleMe: "#FFECE5",
  bubbleOther: "#F5F5F5",
  pillBg: "#F6F6F7",
  accentA: "#C8FA6C",
  accentB: "#7EFDEC",
  orange: "#FE946E",
  peach: "#FFF4EB",
  greenSoft: "#E8F9ED",
};

export const supportStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: supportColors.background,
  },
  screenContent: {
    flex: 1,
  },
  headerWrap: {
    backgroundColor: supportColors.background,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: supportColors.border,
  },
  header: {
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    position: "relative",
  },
  headerSide: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerSideRight: {
    justifyContent: "flex-end",
    gap: 8,
  },
  headerTitleWrap: {
    position: "absolute",
    left: 12,
    right: 12,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    maxWidth: "70%",
  },
  headerBack: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  headerAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#FFE9E0",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  headerAvatarImage: {
    width: 24,
    height: 24,
    borderRadius: 12,
    flexShrink: 0,
  },
  headerAvatarText: {
    color: supportColors.orange,
    fontSize: 11,
    fontWeight: "700",
  },
  headerBackText: {
    color: supportColors.orange,
    fontSize: 14,
    fontWeight: "500",
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: supportColors.text,
    textAlign: "center",
  },
  headerMeta: {
    color: "#C5C5C5",
    fontSize: 15,
    textAlign: "right",
  },
  headerBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FFF0E8",
    borderRadius: 8,
    paddingHorizontal: 8,
    height: 24,
  },
  headerBadgeText: {
    color: supportColors.orange,
    fontSize: 13,
    fontWeight: "500",
  },
  centerMessageWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  centerMessage: {
    color: supportColors.muted,
    fontSize: 15,
    textAlign: "center",
  },
  errorCard: {
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 12,
    backgroundColor: supportColors.dangerBg,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  errorText: {
    color: supportColors.dangerText,
    fontSize: 14,
  },
  retryInlineButton: {
    alignSelf: "flex-start",
    marginTop: 10,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  retryInlineButtonText: {
    color: supportColors.dangerText,
    fontSize: 12,
    fontWeight: "700",
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 6,
  },
  searchWrap: {
    position: "relative",
    flex: 1,
    justifyContent: "center",
  },
  searchIcon: {
    position: "absolute",
    top: 11,
    left: 12,
    zIndex: 1,
  },
  searchInput: {
    height: 40,
    borderRadius: 10,
    backgroundColor: supportColors.pillBg,
    paddingLeft: 38,
    paddingRight: 14,
    color: supportColors.text,
    fontSize: 14,
  },
  searchInputWithClear: {
    paddingRight: 38,
  },
  searchClearButton: {
    position: "absolute",
    right: 12,
    top: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  searchCancelWrap: {
    width: 76,
    height: 40,
    overflow: "hidden",
    justifyContent: "center",
  },
  searchCancelButton: {
    width: 76,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  searchCancelText: {
    color: supportColors.orange,
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
  },
  requestRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 88,
    paddingHorizontal: 16,
    paddingVertical: 15,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E6E6EB",
  },
  requestMain: {
    flex: 1,
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  requestBody: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
  },
  requestTextStack: {
    gap: 2,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: supportColors.orange,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F2F2F3",
  },
  avatarText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  requestNumber: {
    color: supportColors.muted,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  requestTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  requestTitle: {
    color: supportColors.text,
    fontSize: 17,
    fontWeight: "500",
    lineHeight: 20,
  },
  requestDivider: {
    width: StyleSheet.hairlineWidth,
    height: 16,
    backgroundColor: supportColors.border,
  },
  statusPill: {
    borderRadius: 12,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: "600",
  },
  requestSummary: {
    color: supportColors.muted,
    fontSize: 13,
    lineHeight: 17,
  },
  requestMeta: {
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 8,
    paddingLeft: 12,
  },
  countBadge: {
    minWidth: 20,
    height: 20,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF996E",
    paddingHorizontal: 6,
  },
  countBadgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "700",
  },
  requestTime: {
    color: supportColors.muted,
    fontSize: 12,
    lineHeight: 14,
  },
  primaryButtonWrap: {
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 12,
  },
  primaryButton: {
    height: 44,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  requestTypeRow: {
    flexDirection: "row",
    gap: 12,
  },
  requestTypeCard: {
    flex: 1,
    minHeight: 140,
    borderRadius: 28,
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 18,
    overflow: "hidden",
    position: "relative",
    justifyContent: "space-between",
  },
  requestTypeCardProblem: {
    backgroundColor: "#FDECEF",
  },
  requestTypeCardQuestion: {
    backgroundColor: "#FFF4EB",
  },
  requestTypeTitle: {
    fontSize: 22,
    fontWeight: "700",
    zIndex: 2,
  },
  requestTypeAccent: {
    position: "absolute",
    opacity: 0.58,
    zIndex: 1,
  },
  requestTypeGraphicWrap: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#D76E33",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 6,
  },
  requestTypeGraphicWrapProblem: {
    width: 122,
    height: 122,
    borderRadius: 28,
    right: -6,
    bottom: -10,
    transform: [{ rotate: "-10deg" }],
  },
  requestTypeGraphicWrapQuestion: {
    width: 118,
    height: 118,
    borderRadius: 59,
    right: -4,
    bottom: -6,
    transform: [{ rotate: "12deg" }],
  },
  requestTypeMainIconProblem: {
    textShadowColor: "rgba(165, 39, 56, 0.22)",
    textShadowOffset: { width: 0, height: 6 },
    textShadowRadius: 8,
  },
  requestTypeMainIconQuestion: {
    textShadowColor: "rgba(144, 75, 9, 0.2)",
    textShadowOffset: { width: 0, height: 6 },
    textShadowRadius: 10,
  },
  messagesScrollContent: {
    flexGrow: 1,
    justifyContent: "flex-end",
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  messagesScroll: {
    flex: 1,
  },
  messagesDateWrap: {
    alignItems: "center",
    paddingVertical: 12,
  },
  messagesDateBadge: {
    backgroundColor: supportColors.pillBg,
    color: supportColors.text,
    fontSize: 12,
    lineHeight: 16,
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 5,
  },
  messagesColumn: {
    gap: 12,
  },
  messageRowMine: {
    alignItems: "flex-end",
  },
  messageRowOther: {
    alignItems: "flex-start",
  },
  bubble: {
    maxWidth: "80%",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 18,
    paddingRight: 42,
  },
  bubbleMine: {
    backgroundColor: supportColors.bubbleMe,
    borderBottomLeftRadius: 10,
  },
  bubbleOther: {
    backgroundColor: supportColors.bubbleOther,
    borderBottomRightRadius: 10,
  },
  bubbleText: {
    color: supportColors.text,
    fontSize: 14,
    lineHeight: 18,
  },
  bubbleMeta: {
    position: "absolute",
    right: 10,
    bottom: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  bubbleMetaIcon: {
    marginTop: 1,
  },
  bubbleMetaLoader: {
    transform: [{ scale: 0.55 }],
    marginHorizontal: -2,
  },
  bubbleTime: {
    color: "#8D8D8D",
    fontSize: 11,
  },
  messageRetryButton: {
    marginTop: 6,
    borderRadius: 999,
    backgroundColor: "#FFEDEF",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  messageRetryText: {
    color: supportColors.dangerText,
    fontSize: 12,
    fontWeight: "700",
  },
  composerWrap: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: supportColors.border,
    paddingTop: 4,
    backgroundColor: "#FFFFFF",
  },
  composerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
  },
  composerIconButton: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  composerIconDisabled: {
    opacity: 0.7,
  },
  composerInput: {
    flex: 1,
    minHeight: 56,
    maxHeight: 110,
    color: supportColors.text,
    fontSize: 15,
    lineHeight: 20,
    paddingLeft: 4,
    paddingVertical: 0,
    textAlignVertical: "center",
  },
  composerHint: {
    color: supportColors.muted,
    fontSize: 11,
    marginTop: 6,
  },
  disabledComposerText: {
    color: "#C5C5CA",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "center",
  },
  selectedProblemPill: {
    alignSelf: "center",
    borderRadius: 999,
    backgroundColor: supportColors.bubbleMe,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 12,
  },
  selectedProblemText: {
    color: supportColors.text,
    fontSize: 12,
    fontWeight: "500",
  },
  problemPickerScrollContent: {
    flexGrow: 1,
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 30,
  },
  problemPickerSection: {
    gap: 12,
  },
  problemHelpBubble: {
    width: "92%",
    alignSelf: "flex-start",
    borderRadius: 18,
    backgroundColor: supportColors.bubbleOther,
    paddingLeft: 16,
    paddingRight: 64,
    paddingTop: 16,
    paddingBottom: 18,
  },
  problemHelpText: {
    color: supportColors.text,
    fontSize: 16,
    lineHeight: 22,
  },
  problemHelpTime: {
    position: "absolute",
    right: 14,
    bottom: 14,
    color: "#9B9BA1",
    fontSize: 11,
  },
  problemGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 5,
  },
  problemTile: {
    width: "49.3%",
    minHeight: 42,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  problemTileText: {
    fontWeight: "700",
    fontSize: 15,
  },
  actionCard: {
    marginHorizontal: 5,
    marginTop: 9,
    borderRadius: 8,
    backgroundColor: "#FDEBE4",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#F5D9CF",
    paddingHorizontal: 14,
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "rgba(31, 24, 20, 0.18)",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 5,
  },
  actionCardTextWrap: {
    flex: 0,
  },
  actionCardTitle: {
    color: supportColors.orange,
    fontSize: 13,
    fontWeight: "400",
  },
  actionCardText: {
    display: "none",
  },
  outlineButton: {
    height: 48,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: supportColors.border,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  outlineButtonText: {
    color: supportColors.text,
    fontSize: 14,
    fontWeight: "600",
  },
  footerCard: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 18,
  },
  footerCardTitle: {
    color: supportColors.text,
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 30,
  },
  footerCardText: {
    color: supportColors.muted,
    fontSize: 16,
    lineHeight: 22,
    marginTop: 8,
  },
  doubleButtonRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 20,
  },
  ratingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  ratingButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: "center",
    justifyContent: "center",
  },
  multilineInput: {
    minHeight: 96,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: supportColors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: supportColors.text,
    textAlignVertical: "top",
  },
});
