import { StyleSheet } from "react-native";

import {
  PRODUCT_IMAGE_HEIGHT,
  SHEET_OPEN_WIDTH,
} from "@/components/native-bottom-sheet.shared";
import { BrandColors } from "@/constants/theme";

export const styles = StyleSheet.create({
  modalRoot: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalKeyboardContent: {
    flex: 1,
    justifyContent: "flex-end",
  },
  backdropTap: {
    ...StyleSheet.absoluteFillObject,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  backdropBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  backdropTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.16)",
  },
  sheetWrap: {
    alignSelf: "center",
    width: SHEET_OPEN_WIDTH,
    marginBottom: 24,
    borderRadius: 36,
    backgroundColor: "#fff",
    overflow: "hidden",
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 16,
    maxHeight: "90%",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 30,
    elevation: 24,
  },
  sheetWrapProduct: {
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  sheetContentStack: {
    position: "relative",
    overflow: "hidden",
  },
  sheetSkeletonOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#fff",
    zIndex: 1,
  },
  closeBtn: {
    position: "absolute",
    top: 24,
    right: 24,
    width: 24,
    height: 24,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.1)",
    zIndex: 2,
  },
  closeText: {
    color: "#fff",
    fontSize: 14,
    lineHeight: 14,
    fontWeight: "700",
  },
  loginImage: {
    width: 116,
    height: 116,
    alignSelf: "center",
  },
  loginTitle: {
    marginTop: 16,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    color: "#131314",
  },
  loginDescription: {
    marginTop: 8,
    fontSize: 16,
    lineHeight: 22,
    color: "#131314",
  },
  loginButton: {
    marginTop: 16,
    borderRadius: 999,
    backgroundColor: "#FE946E",
    paddingVertical: 12,
    alignItems: "center",
  },
  loginButtonText: {
    color: "#fff",
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "700",
  },
  fallbackTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#131314",
  },
  fallbackText: {
    marginTop: 8,
    fontSize: 14,
    color: "#747479",
  },
  compactInfoSheetWrap: {
    paddingTop: 15,
    paddingHorizontal: 13,
    paddingBottom: 15,
  },
  languageSheetWrap: {
    paddingTop: 15,
    paddingHorizontal: 13,
    paddingBottom: 15,
  },
  languageSheetTitle: {
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "600",
    color: "#131314",
    marginBottom: 4,
  },
  languageSheetDescription: {
    fontSize: 14,
    lineHeight: 18,
    color: "#747479",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
    color: "#131314",
  },
  sectionDescription: {
    marginTop: 4,
    fontSize: 14,
    lineHeight: 18,
    color: "#747479",
  },
  languageList: {
    gap: 8,
  },
  languageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EEF0F5",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#fff",
  },
  radio: {
    width: 16,
    height: 16,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "#D1D5DB",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  radioChecked: {
    borderColor: "#D86F49",
  },
  radioDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#D86F49",
  },
  languageText: {
    fontSize: 16,
    lineHeight: 20,
    color: "#131314",
    fontWeight: "500",
  },
  checkoutAddressSheetWrap: {
    paddingHorizontal: 8,
    paddingTop: 14,
    paddingBottom: 2,
  },
  checkoutAddressSheetTitle: {
    color: "#0B0B0B",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "600",
  },
  checkoutAddressList: {
    maxHeight: 292,
    marginTop: 8,
  },
  checkoutAddressListContent: {
    paddingBottom: 6,
  },
  checkoutAddressOption: {
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#EDEDED",
    paddingVertical: 9,
  },
  checkoutAddressIcon: {
    width: 20,
    height: 20,
  },
  checkoutAddressTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  checkoutAddressTitle: {
    color: "#0B0B0B",
    fontSize: 15,
    lineHeight: 18,
  },
  checkoutAddressSubtitle: {
    marginTop: 2,
    color: "#7C7C7C",
    fontSize: 13,
    lineHeight: 16,
  },
  checkoutAddressRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#D0D0D5",
    alignItems: "center",
    justifyContent: "center",
  },
  checkoutAddressRadioActive: {
    borderColor: BrandColors.primary,
  },
  checkoutAddressRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: BrandColors.primary,
  },
  checkoutAddressEmpty: {
    alignItems: "center",
    paddingVertical: 24,
  },
  checkoutAddressEmptyTitle: {
    color: "#0B0B0B",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  checkoutAddressEmptyText: {
    marginTop: 4,
    color: "#7C7C7C",
    fontSize: 13,
    lineHeight: 16,
    textAlign: "center",
  },
  checkoutAddressActions: {
    flexDirection: "row",
    gap: 8,
    paddingTop: 10,
  },
  checkoutAddressPrimaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: BrandColors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  checkoutAddressSecondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: "#F1F1F3",
    alignItems: "center",
    justifyContent: "center",
  },
  checkoutAddressButtonDisabled: {
    backgroundColor: "#EFEFF1",
  },
  checkoutAddressPrimaryText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  checkoutAddressSecondaryText: {
    color: "#0B0B0B",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
  },
  checkoutAddressDisabledText: {
    color: "#BCBDC2",
  },
  contactCard: {
    marginTop: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EEF0F5",
    backgroundColor: "#F8FAFF",
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  contactLabel: {
    fontSize: 11,
    lineHeight: 14,
    textTransform: "uppercase",
    letterSpacing: 1.6,
    color: "#6B7280",
    fontWeight: "700",
  },
  contactPhone: {
    marginTop: 4,
    fontSize: 20,
    lineHeight: 24,
    color: "#111827",
    fontWeight: "700",
  },
  contactWorkHours: {
    marginTop: 14,
    fontSize: 14,
    lineHeight: 18,
    color: "#6B7280",
  },
  walletSheetWrap: {
    gap: 12,
  },
  walletHeroWrap: {
    borderRadius: 20,
    overflow: "hidden",
    position: "relative",
  },
  walletHeroBase: {
    ...StyleSheet.absoluteFillObject,
  },
  walletHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.92,
  },
  walletHeroContent: {
    padding: 12,
    position: "relative",
    zIndex: 1,
  },
  walletHeroIconWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  walletHeroTitle: {
    marginTop: 8,
    textAlign: "center",
    fontSize: 24,
    lineHeight: 29,
    fontWeight: "600",
    color: "#fff",
  },
  walletHeroDescription: {
    marginTop: 2,
    textAlign: "center",
    fontSize: 14,
    lineHeight: 18,
    color: "#fff",
  },
  walletHeroDivider: {
    marginVertical: 14,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.3)",
  },
  walletInfoCard: {
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
    gap: 2,
  },
  walletInfoLabel: {
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "600",
    textTransform: "uppercase",
    color: "#fff",
  },
  walletInfoAmountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  walletInfoAmount: {
    fontSize: 32,
    lineHeight: 38,
    fontWeight: "700",
    color: "#fff",
  },
  walletInfoNote: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    color: "#fff",
    textAlign: "center",
  },
  walletHelpWrap: {
    paddingHorizontal: 8,
    gap: 6,
  },
  walletHelpTitle: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "600",
    color: "#131314",
  },
  walletHelpText: {
    marginBottom: 3,
    fontSize: 14,
    lineHeight: 20,
    color: "#131314",
  },
  supportCreateSheetWrap: {
    paddingTop: 15,
    paddingHorizontal: 8,
    paddingBottom: 4,
  },
  supportCreateSheetTitle: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    color: "#131314",
  },
  supportCreateSheetDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 18,
    color: "#747479",
  },
  supportCreateCardRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 16,
  },
  supportCreateCard: {
    flex: 1,
    minHeight: 138,
    borderRadius: 28,
    overflow: "hidden",
    position: "relative",
    justifyContent: "flex-start",
  },
  supportCreateProblemCard: {
    backgroundColor: "#FDECEE",
  },
  supportCreateQuestionCard: {
    backgroundColor: "#FFF4EB",
  },
  supportCreateCardPressed: {
    opacity: 0.84,
  },
  supportCreateCardTitle: {
    paddingTop: 16,
    paddingLeft: 20,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    zIndex: 2,
  },
  supportCreateProblemTitle: {
    color: "#E73C50",
  },
  supportCreateQuestionTitle: {
    color: "#FE946E",
  },
  supportDecisionSheetWrap: {
    paddingTop: 15,
    paddingHorizontal: 8,
    paddingBottom: 4,
  },
  supportDecisionTitle: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    color: "#131314",
  },
  supportDecisionDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 18,
    color: "#747479",
  },
  supportDecisionActionStack: {
    gap: 10,
    marginTop: 18,
  },
  supportDecisionSecondaryButton: {
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#ECECEE",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  supportDecisionSecondaryText: {
    color: "#131314",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
  },
  supportDecisionPrimaryButton: {
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  supportDecisionPrimaryText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
  },
  supportDecisionButtonDisabled: {
    opacity: 0.65,
  },
  supportRateCard: {
    marginTop: 18,
    borderRadius: 20,
    backgroundColor: "#F8F8FA",
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  supportRateCardTitle: {
    color: "#131314",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600",
  },
  supportRateRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 14,
  },
  supportRateButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#ECECEE",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  supportRateButtonActive: {
    borderColor: "#FE946E",
    backgroundColor: "#FFF4EB",
  },
  supportRateInput: {
    minHeight: 96,
    marginTop: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#ECECEE",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    lineHeight: 18,
    color: "#131314",
  },
  supportRateActionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  supportRateSkipButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#ECECEE",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  supportRateSkipText: {
    color: "#131314",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
  },
  supportRateSubmitWrap: {
    flex: 1,
  },
  supportCreateProblemImage: {
    position: "absolute",
    right: -12,
    bottom: -14,
    width: 132,
    height: 132,
  },
  supportCreateQuestionImage: {
    position: "absolute",
    right: -10,
    bottom: -20,
    width: 124,
    height: 124,
  },
  supportCreateLoadingText: {
    position: "absolute",
    top: 10,
    right: 10,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "600",
    color: "#FE946E",
  },
  loyaltySheetWrap: {
    gap: 12,
  },
  loyaltyHeaderCard: {
    borderRadius: 20,
    backgroundColor: "#F6F6F7",
    padding: 14,
    gap: 8,
  },
  loyaltyHeadText: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "600",
    color: "#131314",
  },
  loyaltyPoints: {
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "700",
    color: "#131314",
  },
  loyaltyPointsSuffix: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    color: "#131314",
  },
  loyaltySubText: {
    fontSize: 13,
    lineHeight: 18,
    color: "#747479",
  },
  loyaltySubTextAccent: {
    color: "#0B0B0B",
    fontWeight: "600",
  },
  loyaltyProgressTrack: {
    marginTop: 2,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#E6E8EC",
    overflow: "hidden",
  },
  loyaltyProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#16C647",
  },
  loyaltyBody: {
    paddingHorizontal: 8,
    gap: 6,
  },
  loyaltyBodyTitle: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "600",
    color: "#131314",
  },
  loyaltyBodyText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#131314",
  },
  loyaltyCta: {
    minHeight: 44,
    borderRadius: 22,
    backgroundColor: "#0000000D",
    alignItems: "center",
    justifyContent: "center",
  },
  loyaltyCtaText: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    color: "#131314",
  },
  catalogFilterWrap: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 18,
    gap: 18,
  },
  catalogFilterTitle: {
    fontSize: 20,
    lineHeight: 22,
    fontWeight: "700",
    color: "#131314",
  },
  priceInputRow: {
    flexDirection: "row",
    gap: 10,
  },
  priceInputBox: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#131314",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 1,
  },
  priceInputBoxMuted: {
    borderColor: "#CFCFD2",
  },
  priceInputPrefix: {
    fontSize: 16,
    lineHeight: 22,
    color: "#7C7C80",
  },
  priceInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 0,
    fontSize: 16,
    lineHeight: 22,
    color: "#131314",
  },
  priceInputClear: {
    width: 18,
    height: 18,
    borderRadius: 11,
    backgroundColor: "#A9AAAF",
    alignItems: "center",
    justifyContent: "center",
  },
  catalogFilterDivider: {
    height: 1,
    backgroundColor: "#E0E0E0",
  },
  catalogOptionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  catalogOptionPill: {
    borderRadius: 10,
    backgroundColor: "#F4F4F5",
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  catalogOptionPillActive: {
    backgroundColor: "#131314",
  },
  catalogOptionText: {
    fontSize: 16,
    lineHeight: 22,
    color: "#131314",
    fontWeight: "500",
  },
  catalogOptionTextActive: {
    color: "#fff",
  },
  catalogApplyButton: {
    height: 46,
    borderRadius: 24,
    backgroundColor: "#F1F1F2",
    alignItems: "center",
    justifyContent: "center",
  },
  catalogApplyButtonActive: {
    backgroundColor: "#FE946E",
  },
  catalogApplyButtonText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
    color: "#BEBFC2",
  },
  catalogApplyButtonTextActive: {
    color: "#fff",
  },
  productScrollContent: {
    gap: 0,
    paddingBottom: 0,
  },
  productImageWrap: {
    height: PRODUCT_IMAGE_HEIGHT,
    borderRadius: 30,
    overflow: "hidden",
    borderWidth: 0,
    position: "relative",
  },
  productImageTopRow: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  productFavoriteButton: {
    width: 52,
    height: 52,
    borderRadius: 999,
    backgroundColor: "#FE946E",
    alignItems: "center",
    justifyContent: "center",
  },
  productFavoriteButtonActive: {
    backgroundColor: "#FE946E",
  },
  productFavoriteButtonIdle: {
    backgroundColor: "#FE946E",
  },
  productImage: {
    width: "100%",
    height: "100%",
  },
  productImagePressable: {
    width: "100%",
    height: "100%",
  },
  productImageSlide: {
    height: "100%",
  },
  productImageAnimated: {
    width: "100%",
    height: "100%",
  },
  productImageCounter: {
    position: "absolute",
    bottom: 12,
    left: 16,
    right: 16,
  },
  productImageProgress: {
    height: 3,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  productImageProgressSegment: {
    flex: 1,
    height: 3,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.45)",
  },
  productImageProgressSegmentActive: {
    backgroundColor: "#fff",
  },
  productDetails: {
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  priceHeader: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  priceBadges: {
    flexDirection: "row",
    gap: 8,
  },
  cashbackPill: {
    height: 24,
    minWidth: 54,
    borderRadius: 96,
    paddingHorizontal: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  priceCashback: {
    maxWidth: 62,
  },
  cashbackIcon: {
    width: 16,
    height: 16,
  },
  cashbackText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    color: "#131314",
  },
  discountBadge: {
    height: 24,
    minWidth: 47,
    borderRadius: 8,
    backgroundColor: "#E73C50",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  discountBadgeText: {
    color: "#fff",
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "600",
  },
  oldPrice: {
    fontSize: 13,
    lineHeight: 16,
    color: "#7C7C80",
    textDecorationLine: "line-through",
  },
  titleRaised: {
    marginTop: 2,
  },
  productTitle: {
    fontSize: 20,
    lineHeight: 24,
    color: "#00031A",
    fontWeight: "600",
    paddingBottom: 8,
  },
  productDescription: {
    fontSize: 14,
    lineHeight: 18,
    color: "#747479",
  },
  productOrderSection: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 16,
  },
  imageViewerRoot: {
    flex: 1,
    backgroundColor: "#fff",
  },
  imageViewerBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  imageViewerContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 0,
  },
  imageViewerImageWrap: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 0,
    overflow: "visible",
  },
  imageViewerImage: {
    width: "100%",
    height: "100%",
    borderRadius: 0,
  },
  imageViewerClose: {
    position: "absolute",
    top: 56,
    right: 20,
    zIndex: 3,
    width: 44,
    height: 44,
    overflow: "hidden",
    borderRadius: 22,
    backgroundColor: "rgba(0,0,0,0)",
  },
  imageViewerCloseBlur: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  productOrderSectionActive: {
    marginTop: 10,
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: "#fff",
    borderRadius: 28,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: -7 },
    shadowOpacity: 0.09,
    shadowRadius: 20,
    elevation: 10,
  },
  cartSummaryWrap: {
    gap: 0,
  },
  cartSummaryCard: {
    backgroundColor: "#fff",
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    position: "relative",
  },
  cartSummary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cartSummaryLabel: {
    fontSize: 14,
    lineHeight: 18,
    color: "#747479",
  },
  cartSummaryDivider: {
    height: 1,
    backgroundColor: "#EDEDEF",
    marginTop: 14,
    marginBottom: 14,
  },
  productFooterRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 12,
  },
  bottomPriceColumn: {
    flex: 1,
    gap: 2,
    paddingRight: 8,
  },
  bottomOldPrice: {
    fontSize: 13,
    lineHeight: 16,
    color: "#7C7C80",
    textDecorationLine: "line-through",
  },
  bottomFinalPrice: {
    fontSize: 20,
    lineHeight: 24,
    color: "#131314",
    fontWeight: "600",
  },
  quantityRow: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  catalogButton: {
    display: "none",
  },
  catalogButtonText: {
    color: "#FE946E",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
  },
  quantityControl: {
    width: 156,
    height: 45,
    borderRadius: 999,
    backgroundColor: "#F6F6F7",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  quantityButton: {
    width: 48,
    height: 45,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  quantityButtonText: {
    fontSize: 20,
    lineHeight: 24,
    color: "#131314",
    fontWeight: "400",
  },
  quantityValue: {
    minWidth: 32,
    textAlign: "center",
    fontSize: 16,
    lineHeight: 20,
    color: "#131314",
    fontWeight: "600",
  },
  addToCartButton: {
    width: 156,
    height: 45,
    borderRadius: 999,
    backgroundColor: "#FE946E",
    alignItems: "center",
    justifyContent: "center",
  },
  addToCartText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  productErrorWrap: {
    padding: 16,
  },
  productError: {
    color: "#E73C50",
    fontSize: 14,
    lineHeight: 18,
  },
  skeletonRoot: {
    overflow: "hidden",
  },
  skeletonImage: {
    height: PRODUCT_IMAGE_HEIGHT,
    borderRadius: 30,
    backgroundColor: "#F3F2EF",
    overflow: "hidden",
  },
  skeletonDetails: {
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  skeletonBadgeRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
  },
  skeletonCashbackBadge: {
    width: 74,
    height: 24,
    borderRadius: 96,
    backgroundColor: "#EEF0F2",
  },
  skeletonDiscountBadge: {
    width: 58,
    height: 24,
    borderRadius: 8,
    backgroundColor: "#EEF0F2",
  },
  skeletonPriceColumn: {
    gap: 8,
  },
  skeletonPriceSmall: {
    width: 88,
    height: 14,
    borderRadius: 999,
    backgroundColor: "#EEF0F2",
  },
  skeletonPriceLarge: {
    width: 122,
    height: 20,
    borderRadius: 999,
    backgroundColor: "#EEF0F2",
  },
  skeletonTitle: {
    width: "58%",
    height: 24,
    borderRadius: 999,
    backgroundColor: "#EEF0F2",
  },
  skeletonLine: {
    width: "100%",
    height: 16,
    borderRadius: 999,
    backgroundColor: "#EEF0F2",
    marginTop: 14,
  },
  skeletonLineShort: {
    width: "84%",
    height: 16,
    borderRadius: 999,
    backgroundColor: "#EEF0F2",
    marginTop: 8,
  },
  skeletonTitleRaised: {
    marginTop: 0,
  },
  skeletonOrderSection: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 16,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  skeletonButton: {
    width: 156,
    height: 45,
    borderRadius: 999,
    backgroundColor: "#EEF0F2",
  },
  skeletonFavoriteButton: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 52,
    height: 52,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.78)",
  },
  skeletonImageProgress: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 12,
    height: 3,
    flexDirection: "row",
    gap: 5,
  },
  skeletonImageProgressSegment: {
    flex: 1,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.4)",
  },
  skeletonImageProgressActive: {
    flex: 1,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.9)",
  },
});
