import { StyleSheet } from "react-native";

import { BrandColors } from "@/constants/theme";

export const ACCENT_COLOR = BrandColors.primary;

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F6F6F7" },
  header: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 8,
    paddingBottom: 4,
    shadowColor: "#121212",
    shadowOpacity: 0.05,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
    zIndex: 10,
  },
  headerRow: { minHeight: 40, alignItems: "center", justifyContent: "center" },
  backButton: {
    position: "absolute",
    left: 0,
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 1,
  },
  backText: { color: ACCENT_COLOR, fontSize: 16, fontWeight: "400" },
  headerTitle: {
    maxWidth: "60%",
    color: "#111214",
    fontSize: 17,
    fontWeight: "600",
  },
  headerSide: { position: "absolute", right: 0, width: 72 },
  loadingWrap: { flex: 1, alignItems: "center", justifyContent: "center" },
  scroll: { flex: 1 },
  content: { gap: 8 },
  section: { backgroundColor: "#FFFFFF", borderRadius: 20 },
  firstSection: { borderTopLeftRadius: 0, borderTopRightRadius: 0 },
  sectionPadded: { paddingHorizontal: 16, paddingVertical: 12 },
  sectionTitle: {
    color: "#111214",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "600",
  },
  deliveryRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
  },
  deliveryIcon: {
    width: 44,
    height: 72,
    alignItems: "center",
    justifyContent: "center",
  },
  deliveryTextBlock: { flex: 1, minWidth: 0 },
  deliveryTitle: { color: "#0B0B0B", fontSize: 16, lineHeight: 22 },
  deliverySubtitle: { color: "#7C7C7C", fontSize: 14, lineHeight: 16 },
  deliveryChevron: {
    width: 48,
    height: 72,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  viewAllButton: { flexDirection: "row", alignItems: "center", flexShrink: 0 },
  viewAllText: { color: ACCENT_COLOR, fontSize: 15, fontWeight: "500" },
  previewList: { gap: 4, paddingTop: 16 },
  previewItem: {
    width: 62,
    height: 83,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  previewImage: { width: "100%", height: "100%", borderRadius: 8 },
  itemsSheetButton: {
    marginTop: 12,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F5F5F7",
    alignItems: "center",
    justifyContent: "center",
  },
  itemsSheetButtonText: { color: "#111214", fontSize: 14, fontWeight: "600" },
  paymentList: { marginTop: 8, gap: 4 },
  paymentRow: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 0,
    paddingVertical: 12,
  },
  paymentRadioSlot: {
    width: 44,
    minHeight: 36,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    paddingLeft: 16,
  },
  paymentIconSlot: {
    width: 44,
    minHeight: 36,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    paddingLeft: 8,
  },
  radio: {
    marginTop: 2,
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#D0D0D5",
    alignItems: "center",
    justifyContent: "center",
  },
  radioActive: { borderColor: "#1F1F22" },
  radioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#1F1F22",
  },
  paymentTextBlock: { flex: 1, minWidth: 0 },
  paymentTitle: { color: "#1D1E20", fontSize: 16, lineHeight: 20 },
  paymentDescription: { color: "#9899A0", fontSize: 14, lineHeight: 20 },
  bonusTop: {
    position: "relative",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
  },
  bonusRow: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  bonusIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  bonusTextBlock: { flex: 1, minWidth: 0 },
  bonusTitle: { color: "#1D1E20", fontSize: 16, lineHeight: 20 },
  bonusDescription: { color: "#9899A0", fontSize: 14, lineHeight: 20 },
  bonusInputWrap: {
    borderTopWidth: 1,
    borderTopColor: "#ECECEF",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
  },
  inputLabel: { color: "#202124", fontSize: 16, fontWeight: "500" },
  bonusInput: {
    marginTop: 12,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F5F5F7",
    borderWidth: 1,
    borderColor: "transparent",
    paddingHorizontal: 20,
    color: "#202124",
    fontSize: 18,
    textAlignVertical: "center",
  },
  bonusInputError: { borderColor: "#FF5B5B", backgroundColor: "#FFFFFF" },
  bonusHint: { marginTop: 8, color: "#8E8F96", fontSize: 14 },
  bonusHintError: { color: "#FF5B5B" },
  summaryList: { marginTop: 12, gap: 0 },
  summaryRow: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 0,
    paddingVertical: 12,
  },
  summaryLabelWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
  },
  summaryLabel: { color: "#0B0B0B", fontSize: 16, lineHeight: 22 },
  summaryValueWrap: { flexDirection: "row", alignItems: "center", gap: 8 },
  summaryBadge: {
    minWidth: 20,
    height: 20,
    paddingHorizontal: 6,
    borderRadius: 10,
    backgroundColor: "#F0F0F2",
    alignItems: "center",
    justifyContent: "center",
  },
  summaryBadgeText: { color: "#111214", fontSize: 12, fontWeight: "600" },
  summaryValue: {
    color: "#111214",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "400",
  },
  summarySeparator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: "#ECECEF",
    marginHorizontal: -8,
  },
  totalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 12,
  },
  totalLabel: {
    color: "#111214",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "400",
  },
  totalValue: {
    color: "#111214",
    fontSize: 24,
    lineHeight: 29,
    fontWeight: "400",
  },
  errorText: {
    marginHorizontal: 16,
    color: "#FF4D4F",
    fontSize: 14,
    lineHeight: 20,
  },
  emptyText: {
    marginHorizontal: 16,
    color: "#8B8D93",
    fontSize: 14,
    lineHeight: 20,
  },
  footer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    borderTopRadius: 24,
    paddingTop: 12,
    backgroundColor: "#FFFFFF",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#ECECEF",
  },
  footerButton: {
    height: 45,
    borderRadius: 26,
    backgroundColor: ACCENT_COLOR,
    alignItems: "center",
    justifyContent: "center",
  },
  footerButtonDisabled: { backgroundColor: "#F0F0F2" },
  footerButtonText: {
    color: "#FFFFFF",
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "600",
  },
  footerTextDisabled: { color: "#B8B8BD" },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.28)",
  },
  sheetRoot: { flex: 1, justifyContent: "flex-end" },
  sheetCard: {
    maxHeight: "72%",
    marginHorizontal: 8,
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    padding: 16,
  },
  sheetTitle: {
    color: "#111214",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "600",
    marginBottom: 12,
  },
  sheetItem: {
    flexDirection: "row",
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#ECECEF",
  },
  sheetImageWrap: {
    width: 70,
    height: 92,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  sheetImage: { width: "100%", height: "100%" },
  sheetItemInfo: { flex: 1, minWidth: 0 },
  sheetItemTitle: {
    color: "#111214",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600",
  },
  sheetMetaRow: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  sheetMetaLabel: { color: "#8B8D93", fontSize: 13, lineHeight: 18 },
  sheetMetaValueWrap: { flexDirection: "row", alignItems: "center", gap: 6 },
  quantityBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#F2F2F4",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  quantityBadgeText: { color: "#111214", fontSize: 12, fontWeight: "600" },
  sheetDivider: {
    width: StyleSheet.hairlineWidth,
    height: 14,
    backgroundColor: "#D8D8DE",
  },
  sheetMetaValue: {
    color: "#111214",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  colorSwatch: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#D8D8DE",
  },
  sheetCloseButton: {
    height: 52,
    marginHorizontal: 16,
    marginTop: 10,
    borderRadius: 26,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  sheetCloseText: { color: "#111214", fontSize: 16, fontWeight: "600" },
});
